//
//  NSBundle+BuildInfo.m
//  Vibe
//

#import "NSBundle+BuildInfo.h"
#import <sys/sysctl.h>
#import "VibeGitInfo.h" // generated into build/generated by the pre-build script

// The slice's compiled architecture.
#if defined(__arm64__)
static NSString *const kVibeBuildArch = @"arm64";
#elif defined(__x86_64__)
static NSString *const kVibeBuildArch = @"x86_64";
#else
static NSString *const kVibeBuildArch = @"unknown arch";
#endif

// Fallback only: the exact level comes from the plist, since clang exposes
// just these two macros.
#if defined(__OPTIMIZE_SIZE__)
static NSString *const kVibeBuildOptimization = @"optimized for size";
#elif defined(__OPTIMIZE__)
static NSString *const kVibeBuildOptimization = @"optimized";
#else
static NSString *const kVibeBuildOptimization = @"unoptimized";
#endif

// Unset and "" (an unused OTHER_CFLAGS) both read "(none)".
static NSString *VibeBuildSetting(NSDictionary *settings, NSString *key) {
    NSString *value = settings[key];
    if (![value isKindOfClass:NSString.class]) {
        return @"(none)";
    }
    value = [value stringByTrimmingCharactersInSet:NSCharacterSet.whitespaceAndNewlineCharacterSet];
    return value.length > 0 ? value : @"(none)";
}

#if defined(NS_BLOCK_ASSERTIONS)
static NSString *const kVibeBuildAssertions = @"NSAssert off";
#else
static NSString *const kVibeBuildAssertions = @"NSAssert on";
#endif

void VibeLogBuildProvenance(void) {
    NSBundle *bundle = NSBundle.mainBundle;
    LogInfo(@"    Source: %@", bundle.vibeGitString);
    LogInfo(@"     Built: %@", bundle.vibeBuildTimeString);
#if SHOW_EXTENDED_BUILD_INFO
    LogInfo(@"Compiler:  %@", bundle.vibeCompilerString);
    LogInfo(@"Flags:     %@", bundle.vibeBuildFlagsString);
    LogInfo(@"Toolchain: %@", bundle.vibeToolchainString);
    // operatingSystemVersionString is documented as unparseable.
    NSOperatingSystemVersion os = NSProcessInfo.processInfo.operatingSystemVersion;
    char osBuild[32] = "?";
    size_t osBuildSize = sizeof(osBuild);
    sysctlbyname("kern.osversion", osBuild, &osBuildSize, NULL, 0);
#if TARGET_OS_OSX
    LogInfo(@"Host:      macOS %ld.%ld.%ld (%s)", os.majorVersion, os.minorVersion, os.patchVersion, osBuild);
#else
    LogInfo(@"Host:      iOS %ld.%ld.%ld (%s)", os.majorVersion, os.minorVersion, os.patchVersion, osBuild);
#endif
#endif
}

@implementation NSBundle (BuildInfo)

// Not localized: a diagnostic string.
- (NSString *)vibeVersionString {
#if DEBUG
    NSString *configuration = VibeNotLocalized(@"Debug");
#else
    NSString *configuration = VibeNotLocalized(@"Release");
#endif
    NSDictionary *info = self.infoDictionary;
    return [NSString stringWithFormat:VibeNotLocalized(@"%@ (%@) · %@"),
                                      info[@"CFBundleShortVersionString"] ?: @"?",
                                      info[@"CFBundleVersion"] ?: @"?",
                                      configuration];
}

- (NSString *)vibeGitString {
    NSString *commit = @VIBE_GIT_COMMIT;
    if ([commit isEqualToString:@"unknown"]) {
        return @"unknown (not a git checkout)";
    }
    return [NSString stringWithFormat:@"%@ (%s%@)",
                                      commit,
                                      VIBE_GIT_BRANCH,
                                      VIBE_GIT_DIRTY ? @", dirty" : @""];
}

- (NSString *)vibeCompilerString {
    NSDictionary *settings = self.infoDictionary[@"VibeBuild"];
    NSString *optimization = settings ? VibeBuildSetting(settings, @"OptimizationLevel")
                                      : kVibeBuildOptimization;
    return [NSString stringWithFormat:@"clang %s · %@ · %@ · %@ · %@",
                                      __clang_version__,
                                      kVibeBuildArch,
                                      optimization,
                                      __has_feature(objc_arc) ? @"ARC" : @"no ARC",
                                      kVibeBuildAssertions];
}

- (NSString *)vibeBuildFlagsString {
    NSDictionary *settings = self.infoDictionary[@"VibeBuild"];
    if (![settings isKindOfClass:NSDictionary.class]) {
        return @"unknown";
    }
    return [NSString stringWithFormat:@"defines %@ · cflags %@ · c++flags %@ · ldflags %@ · %@ · archs %@ · dead-strip %@ · hardened %@ · sandbox %@",
                                      VibeBuildSetting(settings, @"PreprocessorDefinitions"),
                                      VibeBuildSetting(settings, @"OtherCFlags"),
                                      VibeBuildSetting(settings, @"OtherCPlusPlusFlags"),
                                      VibeBuildSetting(settings, @"OtherLinkerFlags"),
                                      VibeBuildSetting(settings, @"LanguageStandards"),
                                      VibeBuildSetting(settings, @"Architectures"),
                                      VibeBuildSetting(settings, @"DeadCodeStripping"),
                                      VibeBuildSetting(settings, @"HardenedRuntime"),
                                      VibeBuildSetting(settings, @"AppSandbox")];
}

// The build machine is a Mac for both targets.
- (NSString *)vibeToolchainString {
    NSDictionary *info = self.infoDictionary;
#if TARGET_OS_OSX
    NSString *platform = @"macOS", *minimum = info[@"LSMinimumSystemVersion"];
#else
    NSString *platform = @"iOS", *minimum = info[@"MinimumOSVersion"];
#endif
    return [NSString stringWithFormat:@"SDK %@ (%@) · Xcode %@ (%@) · min %@ %@ · on macOS %@",
                                      info[@"DTSDKName"] ?: @"?",
                                      info[@"DTSDKBuild"] ?: @"?",
                                      info[@"DTXcode"] ?: @"?",
                                      info[@"DTXcodeBuild"] ?: @"?",
                                      platform,
                                      minimum ?: @"?",
                                      info[@"BuildMachineOSBuild"] ?: @"?"];
}

- (NSString *)vibeBuildTimeString {
    NSString *executablePath = self.executablePath;
    if (!executablePath) {
        return @"unknown";
    }
    NSDictionary *attributes = [[NSFileManager defaultManager] attributesOfItemAtPath:executablePath
                                                                               error:nil];
    NSDate *modified = attributes[NSFileModificationDate];
    if (!modified) {
        return @"unknown";
    }
    NSDateFormatter *formatter = [[NSDateFormatter alloc] init];
    formatter.locale = [NSLocale localeWithLocaleIdentifier:@"en_US_POSIX"]; // fixed format, not the user's
    formatter.dateFormat = @"yyyy-MM-dd HH:mm:ss ZZZZZ";
    return [formatter stringFromDate:modified];
}

@end
