//
// Created by Christopher Micali on 7/25/26.
// Copyright (c) 2026 Christopher Micali. All rights reserved.
//

#import "NSBundle+BuildInfo.h"
#import "VibeGitInfo.h" // generated into build/generated by the pre-build script

// The architecture this slice was compiled for, not the one it is running
// under: a native arm64 build cannot be translated.
#if defined(__arm64__)
static NSString *const kVibeBuildArch = @"arm64";
#elif defined(__x86_64__)
static NSString *const kVibeBuildArch = @"x86_64";
#else
static NSString *const kVibeBuildArch = @"unknown arch";
#endif

// A fallback only: the exact level comes from GCC_OPTIMIZATION_LEVEL through
// the plist. clang defines no macro for it — -Os and -Oz set both of these,
// -O1 through -O3 set __OPTIMIZE__ alone, and -O0 sets neither — so without
// the plist the level can only be reported as a category.
#if defined(__OPTIMIZE_SIZE__)
static NSString *const kVibeBuildOptimization = @"optimized for size";
#elif defined(__OPTIMIZE__)
static NSString *const kVibeBuildOptimization = @"optimized";
#else
static NSString *const kVibeBuildOptimization = @"unoptimized";
#endif

// A VibeBuild setting for display. Both an unset setting and an empty string —
// an unused OTHER_CFLAGS expands to "" — read as "(none)".
static NSString *VibeBuildSetting(NSDictionary *settings, NSString *key) {
    NSString *value = settings[key];
    if (![value isKindOfClass:NSString.class]) {
        return @"(none)";
    }
    value = [value stringByTrimmingCharactersInSet:NSCharacterSet.whitespaceAndNewlineCharacterSet];
    return value.length > 0 ? value : @"(none)";
}

// ENABLE_NS_ASSERTIONS set to NO, as in Release, defines this and compiles
// NSAssert out.
#if defined(NS_BLOCK_ASSERTIONS)
static NSString *const kVibeBuildAssertions = @"NSAssert off";
#else
static NSString *const kVibeBuildAssertions = @"NSAssert on";
#endif

@implementation NSBundle (BuildInfo)

- (NSString *)vibeVersionString {
#if DEBUG
    NSString *configuration = @"Debug";
#else
    NSString *configuration = @"Release";
#endif
    NSDictionary *info = self.infoDictionary;
    return [NSString stringWithFormat:@"%@ (%@) · %@",
                                      info[@"CFBundleShortVersionString"] ?: @"?",
                                      info[@"CFBundleVersion"] ?: @"?",
                                      configuration];
}

- (NSString *)vibeGitString {
    NSString *commit = @VIBE_GIT_COMMIT;
    if ([commit isEqualToString:@"unknown"]) {
        return @"unknown (not a git checkout)";
    }
    return [NSString stringWithFormat:@"%@ (%s%@)",
                                      commit,
                                      VIBE_GIT_BRANCH,
                                      VIBE_GIT_DIRTY ? @", dirty" : @""];
}

- (NSString *)vibeCompilerString {
    NSDictionary *settings = self.infoDictionary[@"VibeBuild"];
    NSString *optimization = settings ? VibeBuildSetting(settings, @"OptimizationLevel")
                                      : kVibeBuildOptimization;
    return [NSString stringWithFormat:@"clang %s · %@ · %@ · %@ · %@",
                                      __clang_version__,
                                      kVibeBuildArch,
                                      optimization,
                                      __has_feature(objc_arc) ? @"ARC" : @"no ARC",
                                      kVibeBuildAssertions];
}

- (NSString *)vibeBuildFlagsString {
    NSDictionary *settings = self.infoDictionary[@"VibeBuild"];
    if (![settings isKindOfClass:NSDictionary.class]) {
        return @"unknown";
    }
    return [NSString stringWithFormat:@"defines %@ · cflags %@ · c++flags %@ · ldflags %@ · %@ · archs %@ · dead-strip %@ · hardened %@ · sandbox %@",
                                      VibeBuildSetting(settings, @"PreprocessorDefinitions"),
                                      VibeBuildSetting(settings, @"OtherCFlags"),
                                      VibeBuildSetting(settings, @"OtherCPlusPlusFlags"),
                                      VibeBuildSetting(settings, @"OtherLinkerFlags"),
                                      VibeBuildSetting(settings, @"LanguageStandards"),
                                      VibeBuildSetting(settings, @"Architectures"),
                                      VibeBuildSetting(settings, @"DeadCodeStripping"),
                                      VibeBuildSetting(settings, @"HardenedRuntime"),
                                      VibeBuildSetting(settings, @"AppSandbox")];
}

- (NSString *)vibeToolchainString {
    NSDictionary *info = self.infoDictionary;
    return [NSString stringWithFormat:@"SDK %@ (%@) · Xcode %@ (%@) · min macOS %@ · on macOS %@",
                                      info[@"DTSDKName"] ?: @"?",
                                      info[@"DTSDKBuild"] ?: @"?",
                                      info[@"DTXcode"] ?: @"?",
                                      info[@"DTXcodeBuild"] ?: @"?",
                                      info[@"LSMinimumSystemVersion"] ?: @"?",
                                      info[@"BuildMachineOSBuild"] ?: @"?"];
}

- (NSString *)vibeBuildTimeString {
    NSString *executablePath = self.executablePath;
    if (!executablePath) {
        return @"unknown";
    }
    NSDictionary *attributes = [[NSFileManager defaultManager] attributesOfItemAtPath:executablePath
                                                                               error:nil];
    NSDate *modified = attributes[NSFileModificationDate];
    if (!modified) {
        return @"unknown";
    }
    NSDateFormatter *formatter = [[NSDateFormatter alloc] init];
    formatter.locale = [NSLocale localeWithLocaleIdentifier:@"en_US_POSIX"]; // fixed format, not the user's
    formatter.dateFormat = @"yyyy-MM-dd HH:mm:ss ZZZZZ";
    return [formatter stringFromDate:modified];
}

@end
