#!/usr/bin/env bash
#
# Remove generated artifacts so the working tree is pristine:
#   - build/           all xcodebuild / script output (DerivedData, release, ...)
#   - Vibe.xcodeproj   generated by XcodeGen; recreate with `xcodegen generate`
#
# Both are gitignored. As a safety net, Vibe.xcodeproj is only removed if git
# does not track it (so this can't clobber a checked-in project).
set -euo pipefail

cd "$(dirname "$0")/.."

clean_path() {
    local path="$1"
    [[ -e "$path" ]] || { echo "skip $path (absent)"; return 0; }
    if git ls-files --error-unmatch "$path" >/dev/null 2>&1; then
        echo "skip $path (tracked by git)"
        return 0
    fi
    rm -rf "$path"
    echo "🔊 removed $path"
}

clean_path build
clean_path Vibe.xcodeproj

echo "🔊 cleaned"
