#!/bin/bash
#
# Generates VibeGitInfo.h (commit, branch, dirty flag) for NSBundle+BuildInfo's
# launch provenance. The app targets' pre-build phase; also runnable by hand.
#
# Rewritten only when its contents change, so an unchanged git state forces no
# recompile. With no git, every field is "unknown" and the build proceeds.

set -euo pipefail

REPO_ROOT="${SRCROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
OUTPUT_DIR="${VIBE_GENERATED_DIR:-$REPO_ROOT/build/generated}"
OUTPUT="$OUTPUT_DIR/VibeGitInfo.h"

commit="unknown"
branch="unknown"
dirty=0

if command -v git >/dev/null 2>&1 && git -C "$REPO_ROOT" rev-parse --git-dir >/dev/null 2>&1; then
    commit=$(git -C "$REPO_ROOT" rev-parse --short=12 HEAD 2>/dev/null || echo "unknown")
    # A detached HEAD reports "detached" rather than git's literal "HEAD".
    branch=$(git -C "$REPO_ROOT" rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")
    if [ "$branch" = "HEAD" ]; then
        branch="detached"
    fi
    # Anything `git status` shows, untracked files included, counts as dirty.
    if [ -n "$(git -C "$REPO_ROOT" status --porcelain 2>/dev/null)" ]; then
        dirty=1
    fi
fi

contents=$(cat <<EOF
// Generated by scripts/generate-git-info.sh — do not edit, do not commit.
#define VIBE_GIT_COMMIT "$commit"
#define VIBE_GIT_BRANCH "$branch"
#define VIBE_GIT_DIRTY  $dirty
EOF
)

mkdir -p "$OUTPUT_DIR"
if [ ! -f "$OUTPUT" ] || [ "$(cat "$OUTPUT")" != "$contents" ]; then
    printf '%s\n' "$contents" > "$OUTPUT"
    echo "🔊 git info: $commit ($branch$([ "$dirty" = 1 ] && echo ", dirty" || true))"
fi
